export const countries = [
  { code: "+93", countryCode: "AFG", iso2: "AF", engName: "Afghanistan" },
  { code: "+244", countryCode: "AGO", iso2: "AO", engName: "Angola" },
  { code: "+1264", countryCode: "AIA", iso2: "AI", engName: "Anguilla" },
  { code: "+355", countryCode: "ALB", iso2: "AL", engName: "Albania" },
  { code: "+376", countryCode: "AND", iso2: "AD", engName: "Andorra" },
  { code: "+599", countryCode: "ANT", iso2: "AN", engName: "Netherlands Antilles" },
  { code: "+971", countryCode: "ARE", iso2: "AE", engName: "United Arab Emirates" },
  { code: "+54", countryCode: "ARG", iso2: "AR", engName: "Argentina" },
  { code: "+374", countryCode: "ARM", iso2: "AM", engName: "Armenia" },
  { code: "+1684", countryCode: "ASM", iso2: "AS", engName: "American Samoa" },
  { code: "+672", countryCode: "ATA", iso2: "AQ", engName: "Antarctica" },
  { code: "+1268", countryCode: "ATG", iso2: "AG", engName: "Antigua and Barbuda" },
  { code: "+61", countryCode: "AUS", iso2: "AU", engName: "Australia" },
  { code: "+43", countryCode: "AUT", iso2: "AT", engName: "Austria" },
  { code: "+297", countryCode: "AWB", iso2: "AW", engName: "Aruba" },
  { code: "+994", countryCode: "AZE", iso2: "AZ", engName: "Azerbaijan" },
  { code: "+257", countryCode: "BDI", iso2: "BI", engName: "Burundi" },
  { code: "+32", countryCode: "BEL", iso2: "BE", engName: "Belgium" },
  { code: "+229", countryCode: "BEN", iso2: "BJ", engName: "Benin" },
  { code: "+599", countryCode: "BES", iso2: "BQ", engName: "Bonaire/St Eustatius/Saba" },
  { code: "+226", countryCode: "BFA", iso2: "BF", engName: "Burkina Faso" },
  { code: "+880", countryCode: "BGD", iso2: "BD", engName: "Bangladesh" },
  { code: "+359", countryCode: "BGR", iso2: "BG", engName: "Bulgaria" },
  { code: "+973", countryCode: "BHR", iso2: "BH", engName: "Bahrain" },
  { code: "+1242", countryCode: "BHS", iso2: "BS", engName: "Bahamas" },
  { code: "+387", countryCode: "BIH", iso2: "BA", engName: "Bosnia and Herzegovina" },
  { code: "+590", countryCode: "BLM", iso2: "BL", engName: "Saint-Barth?lemy" },
  { code: "+375", countryCode: "BLR", iso2: "BY", engName: "Belarus" },
  { code: "+501", countryCode: "BLZ", iso2: "BZ", engName: "Belize" },
  { code: "+1441", countryCode: "BMU", iso2: "BM", engName: "Bermuda" },
  { code: "+591", countryCode: "BOL", iso2: "BO", engName: "Bolivia" },
  { code: "+55", countryCode: "BRA", iso2: "BR", engName: "Brazil" },
  { code: "+1246", countryCode: "BRB", iso2: "BB", engName: "Barbados" },
  { code: "+673", countryCode: "BRN", iso2: "BN", engName: "Brunei" },
  { code: "+975", countryCode: "BTN", iso2: "BT", engName: "Bhutan" },
  { code: "+267", countryCode: "BWA", iso2: "BW", engName: "Botswana" },
  { code: "+599", countryCode: "C15", iso2: "CW", engName: "Curacao" },
  { code: "+236", countryCode: "CAF", iso2: "CF", engName: "Central African Republic" },
  { code: "+1", countryCode: "CAN", iso2: "CA", engName: "Canada" },
  { code: "+61", countryCode: "CCK", iso2: "CC", engName: "Cocos Islands" },
  { code: "+41", countryCode: "CHE", iso2: "CH", engName: "Switzerland" },
  { code: "+56", countryCode: "CHL", iso2: "CL", engName: "Chile" },
  { code: "+86", countryCode: "CHN", iso2: "CN", engName: "China" },
  { code: "+86", countryCode: "CHN", iso2: "CN", engName: "Hong Kong (S.A.R )" },
  { code: "+225", countryCode: "CIV", iso2: "CI", engName: "Cote D'Ivoire" },
  { code: "+237", countryCode: "CMR", iso2: "CM", engName: "Cameroon" },
  { code: "+243", countryCode: "COD", iso2: "CD", engName: "Congo, The Democratic Republic of the" },
  { code: "+242", countryCode: "COG", iso2: "CG", engName: "Congo, Republic of the" },
  { code: "+682", countryCode: "COK", iso2: "CK", engName: "The Cook Islands" },
  { code: "+57", countryCode: "COL", iso2: "CO", engName: "Colombia" },
  { code: "+269", countryCode: "COM", iso2: "KM", engName: "Comoros" },
  { code: "+238", countryCode: "CPV", iso2: "CV", engName: "Cape Verde" },
  { code: "+506", countryCode: "CRI", iso2: "CR", engName: "Costa Rica" },
  { code: "+53", countryCode: "CUB", iso2: "CU", engName: "Cuba" },
  { code: "+61", countryCode: "CXR", iso2: "CX", engName: "Christmas Island" },
  { code: "+1345", countryCode: "CYM", iso2: "KY", engName: "Cayman Islands" },
  { code: "+357", countryCode: "CYP", iso2: "CY", engName: "Cyprus" },
  { code: "+420", countryCode: "CZE", iso2: "CZ", engName: "Czech Republic" },
  { code: "+49", countryCode: "DEU", iso2: "DE", engName: "Germany" },
  { code: "+253", countryCode: "DJI", iso2: "DJ", engName: "Djibouti" },
  { code: "+767", countryCode: "DMA", iso2: "DM", engName: "Dominica" },
  { code: "+45", countryCode: "DNK", iso2: "DK", engName: "Denmark" },
  { code: "+1809", countryCode: "DOM", iso2: "DO", engName: "Dominican Republic" },
  { code: "+213", countryCode: "DZA", iso2: "DZ", engName: "Algeria" },
  { code: "+593", countryCode: "ECU", iso2: "EC", engName: "Ecuador" },
  { code: "+20", countryCode: "EGY", iso2: "EG", engName: "Egypt" },
  { code: "+291", countryCode: "ERI", iso2: "ER", engName: "Eritrea" },
  { code: "+212", countryCode: "ESH", iso2: "EH", engName: "Western Sahara" },
  { code: "+34", countryCode: "ESP", iso2: "ES", engName: "Spain" },
  { code: "+372", countryCode: "EST", iso2: "EE", engName: "Estonia" },
  { code: "+251", countryCode: "ETH", iso2: "ET", engName: "Ethiopia" },
  { code: "+358", countryCode: "FIN", iso2: "FI", engName: "Finland" },
  { code: "+679", countryCode: "FJI", iso2: "FJ", engName: "Fiji" },
  { code: "+500", countryCode: "FLK", iso2: "FK", engName: "Falkland Islands" },
  { code: "+33", countryCode: "FRA", iso2: "FR", engName: "France" },
  { code: "+298", countryCode: "FRO", iso2: "FO", engName: "Faroe Island" },
  { code: "+691", countryCode: "FSM", iso2: "FM", engName: "Micronesia" },
  { code: "+241", countryCode: "GAB", iso2: "GA", engName: "Gabon" },
  { code: "+44", countryCode: "GBR", iso2: "GB", engName: "United Kingdom" },
  { code: "+995", countryCode: "GEO", iso2: "GE", engName: "Georgia" },
  { code: "+44", countryCode: "GGY", iso2: "GG", engName: "Guernsey" },
  { code: "+233", countryCode: "GHA", iso2: "GH", engName: "Ghana" },
  { code: "+350", countryCode: "GIB", iso2: "GI", engName: "Gibraltar" },
  { code: "+224", countryCode: "GIN", iso2: "GN", engName: "Guinea" },
  { code: "+590", countryCode: "GLP", iso2: "GP", engName: "Guadeloupe" },
  { code: "+220", countryCode: "GMB", iso2: "GM", engName: "Gambia" },
  { code: "+245", countryCode: "GNB", iso2: "GW", engName: "Guinea-Bissau" },
  { code: "+240", countryCode: "GNQ", iso2: "GQ", engName: "Equatorial Guinea" },
  { code: "+1473", countryCode: "GRD", iso2: "GD", engName: "Grenada" },
  { code: "+30", countryCode: "GRE", iso2: "GR", engName: "Greece" },
  { code: "+299", countryCode: "GRL", iso2: "GL", engName: "Greenland" },
  { code: "+502", countryCode: "GTM", iso2: "GT", engName: "Guatemala" },
  { code: "+1671", countryCode: "GUM", iso2: "GU", engName: "Guam" },
  { code: "+592", countryCode: "GUY", iso2: "GY", engName: "Guyana" },
  { code: "+852", countryCode: "HKG", iso2: "HK", engName: "Hong Kong" },
  { code: "+504", countryCode: "HND", iso2: "HN", engName: "Honduras" },
  { code: "+385", countryCode: "HRV", iso2: "HR", engName: "Croatia" },
  { code: "+509", countryCode: "HTI", iso2: "HT", engName: "Haiti" },
  { code: "+36", countryCode: "HUN", iso2: "HU", engName: "Hungary" },
  { code: "+62", countryCode: "IDN", iso2: "ID", engName: "Indonesia" },
  { code: "+44", countryCode: "IMN", iso2: "IM", engName: "Isle of Man" },
  { code: "+91", countryCode: "IND", iso2: "IN", engName: "India" },
  { code: "+246", countryCode: "IOT", iso2: "IO", engName: "British Indian Ocean Territory" },
  { code: "+353", countryCode: "IRL", iso2: "IE", engName: "Ireland" },
  { code: "+98", countryCode: "IRN", iso2: "IR", engName: "Iran" },
  { code: "+964", countryCode: "IRQ", iso2: "IQ", engName: "Iraq" },
  { code: "+354", countryCode: "ISL", iso2: "IS", engName: "Iceland" },
  { code: "+972", countryCode: "ISR", iso2: "IL", engName: "Israel" },
  { code: "+39", countryCode: "ITA", iso2: "IT", engName: "Italy" },
  { code: "+1876", countryCode: "JAM", iso2: "JM", engName: "Jamaica" },
  { code: "+44", countryCode: "JEY", iso2: "JE", engName: "Jersey" },
  { code: "+962", countryCode: "JOR", iso2: "JO", engName: "Jordan" },
  { code: "+81", countryCode: "JPN", iso2: "JP", engName: "Japan" },
  { code: "+7", countryCode: "KAZ", iso2: "KZ", engName: "Kazakhstan" },
  { code: "+254", countryCode: "KEN", iso2: "KE", engName: "Kenya" },
  { code: "+996", countryCode: "KGZ", iso2: "KG", engName: "Kyrgyzstan" },
  { code: "+855", countryCode: "KHM", iso2: "KH", engName: "Cambodia" },
  { code: "+686", countryCode: "KIR", iso2: "KI", engName: "Kiribati" },
  { code: "+1869", countryCode: "KNA", iso2: "KN", engName: "St Kitts and Nevis" },
  { code: "+82", countryCode: "KOR", iso2: "KR", engName: "Korea, Republic of" },
  { code: "+965", countryCode: "KWT", iso2: "KW", engName: "Kuwait" },
  { code: "+856", countryCode: "LAO", iso2: "LA", engName: "Laos" },
  { code: "+961", countryCode: "LBN", iso2: "LB", engName: "Lebanon" },
  { code: "+231", countryCode: "LBR", iso2: "LR", engName: "Liberia" },
  { code: "+218", countryCode: "LBY", iso2: "LY", engName: "Libya" },
  { code: "+1758", countryCode: "LCA", iso2: "LC", engName: "Saint Lucia" },
  { code: "+423", countryCode: "LIE", iso2: "LI", engName: "Liechtenstein" },
  { code: "+94", countryCode: "LKA", iso2: "LK", engName: "Sri Lanka" },
  { code: "+266", countryCode: "LSO", iso2: "LS", engName: "Lesotho" },
  { code: "+370", countryCode: "LTU", iso2: "LT", engName: "Lithuania" },
  { code: "+352", countryCode: "LUX", iso2: "LU", engName: "Luxembourg" },
  { code: "+371", countryCode: "LVA", iso2: "LV", engName: "Latvia" },
  { code: "+853", countryCode: "MAC", iso2: "MO", engName: "Macao (S.A.R.)" },
  { code: "+590", countryCode: "MAF", iso2: "MF", engName: "St Maarten" },
  { code: "+590", countryCode: "MAF", iso2: "MF", engName: "St Martin" },
  { code: "+212", countryCode: "MAR", iso2: "MA", engName: "Morocco" },
  { code: "+377", countryCode: "MCO", iso2: "MC", engName: "Monaco" },
  { code: "+373", countryCode: "MDA", iso2: "MD", engName: "Moldova" },
  { code: "+261", countryCode: "MDG", iso2: "MG", engName: "Madagascar" },
  { code: "+960", countryCode: "MDV", iso2: "MV", engName: "Maldives" },
  { code: "+52", countryCode: "MEX", iso2: "MX", engName: "Mexico" },
  { code: "+692", countryCode: "MHL", iso2: "MH", engName: "Marshall Islands" },
  { code: "+389", countryCode: "MKD", iso2: "MK", engName: "Macedonia" },
  { code: "+223", countryCode: "MLI", iso2: "ML", engName: "Mali" },
  { code: "+356", countryCode: "MLT", iso2: "MT", engName: "Malta" },
  { code: "+95", countryCode: "MMR", iso2: "MM", engName: "Burma" },
  { code: "+382", countryCode: "MNE", iso2: "ME", engName: "Montenegro" },
  { code: "+976", countryCode: "MNG", iso2: "MN", engName: "Mongolia" },
  { code: "+1670", countryCode: "MNP", iso2: "MP", engName: "Northern Mariana Islands" },
  { code: "+258", countryCode: "MOZ", iso2: "MZ", engName: "Mozambique" },
  { code: "+222", countryCode: "MRT", iso2: "MR", engName: "Mauritania" },
  { code: "+1664", countryCode: "MSR", iso2: "MS", engName: "Montserrat" },
  { code: "+230", countryCode: "MUS", iso2: "MU", engName: "Mauritius" },
  { code: "+265", countryCode: "MWI", iso2: "MW", engName: "Malawi" },
  { code: "+60", countryCode: "MYS", iso2: "MY", engName: "Malaysia" },
  { code: "+262", countryCode: "MYT", iso2: "YT", engName: "Mayotte" },
  { code: "+264", countryCode: "NAM", iso2: "NA", engName: "Namibia" },
  { code: "+687", countryCode: "NCL", iso2: "NC", engName: "New Caledonia" },
  { code: "+227", countryCode: "NER", iso2: "NE", engName: "Niger" },
  { code: "+234", countryCode: "NGA", iso2: "NG", engName: "Nigeria" },
  { code: "+505", countryCode: "NIC", iso2: "NI", engName: "Nicaragua" },
  { code: "+683", countryCode: "NIU", iso2: "NU", engName: "Niue" },
  { code: "+31", countryCode: "NLD", iso2: "NL", engName: "Netherlands" },
  { code: "+47", countryCode: "NOR", iso2: "NO", engName: "Norway" },
  { code: "+977", countryCode: "NPL", iso2: "NP", engName: "Nepal" },
  { code: "+674", countryCode: "NRU", iso2: "NR", engName: "Nauru" },
  { code: "+64", countryCode: "NZL", iso2: "NZ", engName: "New Zealand" },
  { code: "+968", countryCode: "OMN", iso2: "OM", engName: "Oman" },
  { code: "+92", countryCode: "PAK", iso2: "PK", engName: "Pakistan" },
  { code: "+507", countryCode: "PAN", iso2: "PA", engName: "Panama" },
  { code: "+64", countryCode: "PCN", iso2: "PN", engName: "Pitcairn Island" },
  { code: "+51", countryCode: "PER", iso2: "PE", engName: "Peru" },
  { code: "+63", countryCode: "PHL", iso2: "PH", engName: "Philippines" },
  { code: "+970", countryCode: "PSE", iso2: "PS", engName: "Palestine" },
  { code: "+680", countryCode: "PLW", iso2: "PW", engName: "Palau" },
  { code: "+675", countryCode: "PNG", iso2: "PG", engName: "Papua New Guinea" },
  { code: "+48", countryCode: "POL", iso2: "PL", engName: "Poland" },
  { code: "+1787", countryCode: "PRI", iso2: "PR", engName: "Puerto Rico" },
  { code: "+850", countryCode: "PRK", iso2: "KP", engName: "Korea, Democratic people's Republic of" },
  { code: "+351", countryCode: "PRT", iso2: "PT", engName: "Portugal" },
  { code: "+595", countryCode: "PRY", iso2: "PY", engName: "Paraguay" },
  { code: "+689", countryCode: "PYF", iso2: "PF", engName: "French Polynesia" },
  { code: "+974", countryCode: "QAT", iso2: "QA", engName: "Qatar" },
  { code: "+262", countryCode: "REU", iso2: "RE", engName: "Reunion Island" },
  { code: "+383", countryCode: "RKS", iso2: "XK", engName: "Kosovo" },
  { code: "+40", countryCode: "ROU", iso2: "RO", engName: "Romania" },
  { code: "+7", countryCode: "RUS", iso2: "RU", engName: "Russia" },
  { code: "+250", countryCode: "RWA", iso2: "RW", engName: "Rwanda" },
  { code: "+966", countryCode: "SAU", iso2: "SA", engName: "Saudi Arabia" },
  { code: "+249", countryCode: "SDN", iso2: "SD", engName: "Sudan" },
  { code: "+221", countryCode: "SEN", iso2: "SN", engName: "Senegal" },
  { code: "+65", countryCode: "SGP", iso2: "SG", engName: "Singapore" },
  { code: "+500", countryCode: "SGS", iso2: "GS", engName: "South Georgia And The South Sandwich Islands" },
  { code: "+290", countryCode: "SHN", iso2: "SH", engName: "St Helena, Ascension and Tristan da Cunha" },
  { code: "+47", countryCode: "SJM", iso2: "SJ", engName: "Svalbard and Jan Mayen" },
  { code: "+677", countryCode: "SLB", iso2: "SB", engName: "Solomon Islands" },
  { code: "+232", countryCode: "SLE", iso2: "SL", engName: "Sierra Leone" },
  { code: "+503", countryCode: "SLV", iso2: "SV", engName: "El Salvador" },
  { code: "+378", countryCode: "SMR", iso2: "SM", engName: "San Marino" },
  { code: "+252", countryCode: "SOM", iso2: "SO", engName: "Somalia" },
  { code: "+508", countryCode: "SPM", iso2: "PM", engName: "Saint Pierre and Miquelon" },
  { code: "+381", countryCode: "SRB", iso2: "RS", engName: "Serbia" },
  { code: "+211", countryCode: "SSD", iso2: "SS", engName: "South Sudan" },
  { code: "+239", countryCode: "STP", iso2: "ST", engName: "Sao Tome And Principe" },
  { code: "+597", countryCode: "SUR", iso2: "SR", engName: "Suriname" },
  { code: "+421", countryCode: "SVK", iso2: "SK", engName: "Slovakia" },
  { code: "+386", countryCode: "SVN", iso2: "SI", engName: "Slovenia" },
  { code: "+46", countryCode: "SWE", iso2: "SE", engName: "Sweden" },
  { code: "+268", countryCode: "SWZ", iso2: "SZ", engName: "Swaziland" },
  { code: "+1721", countryCode: "SXM", iso2: "SX", engName: "Sint Maarten" },
  { code: "+248", countryCode: "SYC", iso2: "SC", engName: "Seychelles" },
  { code: "+963", countryCode: "SYR", iso2: "SY", engName: "Syria" },
  { code: "+1649", countryCode: "TCA", iso2: "TC", engName: "Turks And Caicos Islands" },
  { code: "+235", countryCode: "TCD", iso2: "TD", engName: "Chad" },
  { code: "+228", countryCode: "TGO", iso2: "TG", engName: "Togo" },
  { code: "+66", countryCode: "THA", iso2: "TH", engName: "Thailand" },
  { code: "+992", countryCode: "TJK", iso2: "TJ", engName: "Tajikistan" },
  { code: "+690", countryCode: "TKL", iso2: "TK", engName: "Tokelau" },
  { code: "+993", countryCode: "TKM", iso2: "TM", engName: "Turkmenistan" },
  { code: "+670", countryCode: "TLS", iso2: "TL", engName: "Timor Leste" },
  { code: "+676", countryCode: "TON", iso2: "TO", engName: "Tonga" },
  { code: "+1868", countryCode: "TTO", iso2: "TT", engName: "Trinidad And Tobago" },
  { code: "+216", countryCode: "TUN", iso2: "TN", engName: "Tunisia" },
  { code: "+90", countryCode: "TUR", iso2: "TR", engName: "Turkey" },
  { code: "+688", countryCode: "TUV", iso2: "TV", engName: "Tuvalu" },
  { code: "+886", countryCode: "TWN", iso2: "TW", engName: "Chinese (Taipei)" },
  { code: "+255", countryCode: "TZA", iso2: "TZ", engName: "Tanzania" },
  { code: "+256", countryCode: "UGA", iso2: "UG", engName: "Uganda" },
  { code: "+380", countryCode: "UKR", iso2: "UA", engName: "Ukraine" },
  { code: "+598", countryCode: "URY", iso2: "UY", engName: "Uruguay" },
  { code: "+1", countryCode: "USA", iso2: "US", engName: "United States" },
  { code: "+998", countryCode: "UZB", iso2: "UZ", engName: "Uzbekistan" },
  { code: "+379", countryCode: "VAT", iso2: "VA", engName: "Vatican City" },
  { code: "+1784", countryCode: "VCT", iso2: "VC", engName: "St Vincent And The Grenadines" },
  { code: "+58", countryCode: "VEN", iso2: "VE", engName: "Venezuela" },
  { code: "+1340", countryCode: "VIR", iso2: "VI", engName: "U.S. Virgin Islands" },
  { code: "+1284", countryCode: "VIS", iso2: "VG", engName: "British Virgin Islands" },
  { code: "+84", countryCode: "VNM", iso2: "VN", engName: "Vietnam" },
  { code: "+678", countryCode: "VUT", iso2: "VU", engName: "Vanuatu" },
  { code: "+681", countryCode: "WLF", iso2: "WF", engName: "Wallis and Futuna" },
  { code: "+685", countryCode: "WSM", iso2: "WS", engName: "Samoa" },
  { code: "+967", countryCode: "YEM", iso2: "YE", engName: "Yemen" },
  { code: "+27", countryCode: "ZAF", iso2: "ZA", engName: "South Africa" },
  { code: "+260", countryCode: "ZMB", iso2: "ZM", engName: "Zambia" },
  { code: "+263", countryCode: "ZWE", iso2: "ZW", engName: "Zimbabwe" },
];
